# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripinformation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='end_gas_level',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='end_miles',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='end_point',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='start_gas_level',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='start_miles',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='start_point',
        ),
        migrations.AddField(
            model_name='tripinformation',
            name='fuel_status',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripinformation',
            name='load',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripinformation',
            name='mph',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripinformation',
            name='throttle',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trips',
            name='end_fuel',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trips',
            name='start_fuel',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
