# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('rpm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_point', models.CharField(max_length=200)),
                ('end_point', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_miles', models.IntegerField(null=True)),
                ('end_miles', models.IntegerField(null=True)),
                ('start_gas_level', models.IntegerField(null=True)),
                ('end_gas_level', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tripinformation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Trips'),
        ),
    ]
